# Generated by Django 5.0.7 on 2026-01-17 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_booking_room_alter_booking_room_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guestprofile',
            options={'verbose_name': 'Профиль пациента', 'verbose_name_plural': 'Профили пациентов'},
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='address',
            field=models.TextField(blank=True, max_length=200, verbose_name='Адрес проживания'),
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='allergies',
            field=models.TextField(blank=True, max_length=500, verbose_name='Аллергии'),
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('O+', 'O(I) Rh+'), ('O-', 'O(I) Rh-'), ('A+', 'A(II) Rh+'), ('A-', 'A(II) Rh-'), ('B+', 'B(III) Rh+'), ('B-', 'B(III) Rh-'), ('AB+', 'AB(IV) Rh+'), ('AB-', 'AB(IV) Rh-')], max_length=3, verbose_name='Группа крови'),
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='chronic_diseases',
            field=models.TextField(blank=True, max_length=500, verbose_name='Хронические заболевания'),
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='contraindications',
            field=models.TextField(blank=True, max_length=500, verbose_name='Противопоказания к процедурам'),
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='drug_intolerance',
            field=models.TextField(blank=True, max_length=500, verbose_name='Лекарственная непереносимость'),
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=100, verbose_name='Контакт для экстренной связи'),
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон экстренной связи'),
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='is_profile_complete',
            field=models.BooleanField(default=False, verbose_name='Профиль заполнен'),
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='medical_book_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Номер мед. книжки'),
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='middle_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='need_transfer',
            field=models.BooleanField(default=False, verbose_name='Нужен трансфер'),
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='oms_policy',
            field=models.CharField(blank=True, max_length=16, verbose_name='Полис ОМС'),
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='passport_issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи'),
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='passport_issued_by',
            field=models.TextField(blank=True, max_length=200, verbose_name='Кем выдан'),
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='passport_number',
            field=models.CharField(blank=True, max_length=6, verbose_name='Номер паспорта'),
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='passport_series',
            field=models.CharField(blank=True, max_length=4, verbose_name='Серия паспорта'),
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='preferred_diet',
            field=models.CharField(choices=[('standard', 'Общий стол'), ('dietary', 'Диетическое'), ('vegetarian', 'Вегетарианское'), ('diabetic', 'Диабетическое'), ('salt_free', 'Бессолевое'), ('gluten_free', 'Безглютеновое')], default='standard', max_length=20, verbose_name='Предпочитаемое питание'),
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='snils',
            field=models.CharField(blank=True, help_text='Формат: XXX-XXX-XXX XX', max_length=14, verbose_name='СНИЛС'),
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='special_requests',
            field=models.TextField(blank=True, max_length=500, verbose_name='Особые пожелания'),
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='guestprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='guestprofile',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='guestprofile',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='guestprofile',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
    ]
