# Generated by Django 5.0.7 on 2026-01-27 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_guestprofile_options_guestprofile_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название процедуры')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание')),
                ('duration', models.PositiveIntegerField(verbose_name='Длительность (минут)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Стоимость')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('contraindications', models.TextField(blank=True, max_length=500, verbose_name='Противопоказания')),
                ('preparation', models.TextField(blank=True, max_length=500, verbose_name='Подготовка к процедуре')),
            ],
            options={
                'verbose_name': 'Процедура',
                'verbose_name_plural': 'Процедуры',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProcedureCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('description', models.TextField(max_length=500, verbose_name='Описание')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Категория процедур',
                'verbose_name_plural': 'Категории процедур',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=200, verbose_name='Специализация')),
                ('qualification', models.CharField(max_length=200, verbose_name='Квалификация')),
                ('experience', models.PositiveIntegerField(verbose_name='Стаж (лет)')),
                ('bio', models.TextField(blank=True, max_length=1000, verbose_name='Биография')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='doctors/', verbose_name='Фото')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('procedures', models.ManyToManyField(to='accounts.procedure', verbose_name='Проводимые процедуры')),
            ],
            options={
                'verbose_name': 'Врач',
                'verbose_name_plural': 'Врачи',
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_date', models.DateField(verbose_name='Дата поступления')),
                ('discharge_date', models.DateField(blank=True, null=True, verbose_name='Дата выписки')),
                ('diagnosis', models.TextField(max_length=1000, verbose_name='Диагноз')),
                ('treatment_plan', models.TextField(max_length=2000, verbose_name='План лечения')),
                ('recommendations', models.TextField(blank=True, max_length=1000, verbose_name='Рекомендации')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('attending_doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.doctor', verbose_name='Лечащий врач')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='accounts.booking', verbose_name='Бронирование')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='accounts.guestprofile', verbose_name='Пациент')),
            ],
            options={
                'verbose_name': 'Медицинская карта',
                'verbose_name_plural': 'Медицинские карты',
            },
        ),
        migrations.AddField(
            model_name='procedure',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='accounts.procedurecategory', verbose_name='Категория'),
        ),
        migrations.CreateModel(
            name='ScheduleSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('mon', 'Понедельник'), ('tue', 'Вторник'), ('wed', 'Среда'), ('thu', 'Четверг'), ('fri', 'Пятница'), ('sat', 'Суббота'), ('sun', 'Воскресенье')], max_length=3, verbose_name='День недели')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('max_appointments', models.PositiveIntegerField(default=1, verbose_name='Максимум записей')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_slots', to='accounts.doctor', verbose_name='Врач')),
            ],
            options={
                'verbose_name': 'Слот расписания',
                'verbose_name_plural': 'Слоты расписания',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(verbose_name='Дата приема')),
                ('appointment_time', models.TimeField(verbose_name='Время приема')),
                ('status', models.CharField(choices=[('scheduled', 'Запланирована'), ('completed', 'Выполнена'), ('cancelled', 'Отменена'), ('no_show', 'Не явился')], default='scheduled', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, max_length=500, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='accounts.guestprofile', verbose_name='Пациент')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='accounts.doctor', verbose_name='Врач')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.procedure', verbose_name='Процедура')),
                ('schedule_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.scheduleslot', verbose_name='Временной слот')),
            ],
            options={
                'verbose_name': 'Запись на процедуру',
                'verbose_name_plural': 'Записи на процедуры',
                'ordering': ['appointment_date', 'appointment_time'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата выполнения')),
                ('result', models.TextField(max_length=500, verbose_name='Результат/наблюдения')),
                ('doctor_notes', models.TextField(blank=True, max_length=500, verbose_name='Заметки врача')),
                ('next_date', models.DateField(blank=True, null=True, verbose_name='Следующая дата')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.appointment', verbose_name='Запись на процедуру')),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_entries', to='accounts.medicalrecord', verbose_name='Медицинская карта')),
            ],
            options={
                'verbose_name': 'Запись о лечении',
                'verbose_name_plural': 'Записи о лечении',
                'ordering': ['-performed_at'],
            },
        ),
    ]
