# Generated by Django 5.0.7 on 2026-01-28 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_procedure_procedurecategory_doctor_medicalrecord_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guestprofile',
            options={'permissions': [('can_view_sensitive_data', 'Может просматривать чувствительные данные'), ('can_verify_documents', 'Может проверять документы')], 'verbose_name': 'Профиль пациента', 'verbose_name_plural': 'Профили пациентов'},
        ),
        migrations.RemoveField(
            model_name='guestprofile',
            name='medical_book_number',
        ),
        migrations.RemoveField(
            model_name='guestprofile',
            name='oms_policy',
        ),
        migrations.RemoveField(
            model_name='guestprofile',
            name='passport_issue_date',
        ),
        migrations.RemoveField(
            model_name='guestprofile',
            name='passport_issued_by',
        ),
        migrations.RemoveField(
            model_name='guestprofile',
            name='passport_number',
        ),
        migrations.RemoveField(
            model_name='guestprofile',
            name='passport_series',
        ),
        migrations.RemoveField(
            model_name='guestprofile',
            name='snils',
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='document_status',
            field=models.CharField(choices=[('not_uploaded', 'Не загружены'), ('pending', 'На проверке'), ('verified', 'Проверены'), ('rejected', 'Отклонены')], default='not_uploaded', max_length=20, verbose_name='Статус документов'),
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='document_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки'),
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='document_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_profiles', to=settings.AUTH_USER_MODEL, verbose_name='Кем проверены'),
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='passport_masked',
            field=models.CharField(blank=True, max_length=20, verbose_name='Паспорт (маскированный)'),
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='snils_masked',
            field=models.CharField(blank=True, max_length=20, verbose_name='СНИЛС (маскированный)'),
        ),
        migrations.CreateModel(
            name='EncryptedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('passport', 'Паспорт'), ('snils', 'СНИЛС'), ('oms', 'Полис ОМС'), ('medical', 'Медицинская книжка'), ('other', 'Другое')], max_length=20)),
                ('encrypted_data', models.TextField(blank=True, verbose_name='Зашифрованные данные')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('verified', models.BooleanField(default=False, verbose_name='Проверено')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.guestprofile')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_document_files', to=settings.AUTH_USER_MODEL, verbose_name='Загружено')),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_document_files', to=settings.AUTH_USER_MODEL, verbose_name='Кем проверен')),
            ],
            options={
                'verbose_name': 'Зашифрованный документ',
                'verbose_name_plural': 'Зашифрованные документы',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
